payment-dev/samples/WebApplicationSample/Controllers/WeChatPayController.cs
using System.Text.Json;
using System.Threading.Tasks;
using Essensoft.AspNetCore.Payment.WeChatPay;
using Essensoft.AspNetCore.Payment.WeChatPay.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class WeChatPayController : Controller
    {
        private readonly IWeChatPayClient _client;
        private readonly IOptions<WeChatPayOptions> _optionsAccessor;

        public WeChatPayController(IWeChatPayClient client, IOptions<WeChatPayOptions> optionsAccessor)
        {
            _client = client;
            _optionsAccessor = optionsAccessor;
        }

        /// <summary>
        /// 微信支付指引页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 刷卡支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult MicroPay()
        {
            return View();
        }

        /// <summary>
        /// 刷卡支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> MicroPay(WeChatPayMicroPayViewModel viewModel)
        {
            var request = new WeChatPayMicroPayRequest
            {
                Body = viewModel.Body,
                OutTradeNo = viewModel.OutTradeNo,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                AuthCode = viewModel.AuthCode
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 公众号支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult PubPay()
        {
            return View();
        }

        /// <summary>
        /// 公众号支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> PubPay(WeChatPayPubPayViewModel viewModel)
        {
            var request = new WeChatPayUnifiedOrderRequest
            {
                Body = viewModel.Body,
                OutTradeNo = viewModel.OutTradeNo,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                NotifyUrl = viewModel.NotifyUrl,
                TradeType = viewModel.TradeType,
                OpenId = viewModel.OpenId
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            if (response.ReturnCode == WeChatPayCode.Success && response.ResultCode == WeChatPayCode.Success)
            {
                var req = new WeChatPayJsApiSdkRequest
                {
                    Package = "prepay_id=" + response.PrepayId
                };

                var parameter = await _client.ExecuteAsync(req, _optionsAccessor.Value);
                
                // 将参数(parameter)给 公众号前端 让他在微信内H5调起支付(https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_7&index=6)
                ViewData["parameter"] = JsonSerializer.Serialize(parameter);
                ViewData["response"] = response.ResponseBody;
                return View();
            }
            
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 扫码支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult QrCodePay()
        {
            return View();
        }

        /// <summary>
        /// 扫码支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> QrCodePay(WeChatPayQrCodePayViewModel viewModel)
        {
            var request = new WeChatPayUnifiedOrderRequest
            {
                Body = viewModel.Body,
                OutTradeNo = viewModel.OutTradeNo,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                NotifyUrl = viewModel.NotifyUrl,
                TradeType = viewModel.TradeType
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            
            // response.CodeUrl 给前端生成二维码
            ViewData["qrcode"] = response.CodeUrl;
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// APP支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AppPay()
        {
            return View();
        }

        /// <summary>
        /// APP支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AppPay(WeChatPayAppPayViewModel viewModel)
        {
            var request = new WeChatPayUnifiedOrderRequest
            {
                Body = viewModel.Body,
                OutTradeNo = viewModel.OutTradeNo,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                NotifyUrl = viewModel.NotifyUrl,
                TradeType = viewModel.TradeType
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            if (response.ReturnCode == WeChatPayCode.Success && response.ResultCode == WeChatPayCode.Success)
            {
                var req = new WeChatPayAppSdkRequest
                {
                    PrepayId = response.PrepayId
                };

                var parameter = await _client.ExecuteAsync(req, _optionsAccessor.Value);
                
                // 将参数(parameter)给 ios/android端 让他调起微信APP(https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=8_5)
                ViewData["parameter"] = JsonSerializer.Serialize(parameter);
                ViewData["response"] = response.ResponseBody;
                return View();
            }

            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// H5支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult H5Pay()
        {
            return View();
        }

        /// <summary>
        /// H5支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> H5Pay(WeChatPayH5PayViewModel viewModel)
        {
            var request = new WeChatPayUnifiedOrderRequest
            {
                Body = viewModel.Body,
                OutTradeNo = viewModel.OutTradeNo,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                NotifyUrl = viewModel.NotifyUrl,
                TradeType = viewModel.TradeType
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

            // mweb_url为拉起微信支付收银台的中间页面，可通过访问该url来拉起微信客户端，完成支付,mweb_url的有效期为5分钟。
            return Redirect(response.MwebUrl);
        }

        /// <summary>
        /// 小程序支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult LiteAppPay()
        {
            return View();
        }

        /// <summary>
        /// 小程序支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> LiteAppPay(WeChatPayLiteAppPayViewModel viewModel)
        {
            var request = new WeChatPayUnifiedOrderRequest
            {
                Body = viewModel.Body,
                OutTradeNo = viewModel.OutTradeNo,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                NotifyUrl = viewModel.NotifyUrl,
                TradeType = viewModel.TradeType,
                OpenId = viewModel.OpenId
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            if (response.ReturnCode == WeChatPayCode.Success && response.ResultCode == WeChatPayCode.Success)
            {
                var req = new WeChatPayLiteAppSdkRequest
                {
                    Package = "prepay_id=" + response.PrepayId
                };
                
                var parameter = await _client.ExecuteAsync(req, _optionsAccessor.Value);

                // 将参数(parameter)给 小程序前端 让他调起支付API(https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5)
                ViewData["parameter"] = JsonSerializer.Serialize(parameter);
                ViewData["response"] = response.ResponseBody;
                return View();
            }

            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 查询订单
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult OrderQuery()
        {
            return View();
        }

        /// <summary>
        /// 查询订单
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> OrderQuery(WeChatPayOrderQueryViewModel viewModel)
        {
            var request = new WeChatPayOrderQueryRequest
            {
                TransactionId = viewModel.TransactionId,
                OutTradeNo = viewModel.OutTradeNo
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);

payment-dev/samples/WebApplicationSample/Views/WeChatPay/CloseOrder.cshtml
@model WeChatPayCloseOrderViewModel
@{
    ViewData["Title"] = "关闭订单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPay" asp-action="CloseOrder">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

payment-dev/samples/WebApplicationSample/Views/WeChatPay/DownloadBill.cshtml
@model WeChatPayDownloadBillViewModel
@{
    ViewData["Title"] = "下载对账单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPay" asp-action="DownloadBill">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BillDate"></label>
                <input type="text" class="form-control" asp-for="BillDate" />
            </div>
            <div class="form-group">
                <label asp-for="BillType"></label>
                <input type="text" class="form-control" asp-for="BillType" value="ALL" />
            </div>
            <div class="form-group">
                <label asp-for="TarType"></label>
                <input type="text" class="form-control" asp-for="TarType" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

payment-dev/samples/WebApplicationSample/Views/WeChatPay/DownloadFundFlow.cshtml
@model WeChatPayDownloadFundFlowViewModel
@{
    ViewData["Title"] = "下载资金账单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPay" asp-action="DownloadFundFlow">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BillDate"></label>
                <input type="text" class="form-control" asp-for="BillDate" />
            </div>
            <div class="form-group">
                <label asp-for="AccountType"></label>
                <input type="text" class="form-control" asp-for="AccountType" value="Basic" />
            </div>
            <div class="form-group">
                <label asp-for="TarType"></label>
                <input type="text" class="form-control" asp-for="TarType" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

payment-dev/samples/WebApplicationSample/Views/WeChatPay/GetPublicKey.cshtml
@{
    ViewData["Title"] = "获取RSA加密公钥";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPay" asp-action="GetPublicKey">
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>

payment-dev/samples/WebApplicationSample/Views/WeChatPay/Index.cshtml
@{
    ViewData["Title"] = "微信支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">首页</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">产品</th>
            <th scope="col">接口</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>刷卡支付-提交刷卡支付</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_10&index=1" target="_blank">https://api.mch.weixin.qq.com/pay/micropay</a></td>
            <td><a asp-controller="WeChatPay" asp-action="MicroPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>公众号支付-统一下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1" target="_blank">https://api.mch.weixin.qq.com/pay/unifiedorder</a></td>
            <td><a asp-controller="WeChatPay" asp-action="PubPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>扫码支付-统一下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=9_1" target="_blank">https://api.mch.weixin.qq.com/pay/unifiedorder</a></td>
            <td><a asp-controller="WeChatPay" asp-action="QrCodePay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>APP支付-统一下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_1" target="_blank">https://api.mch.weixin.qq.com/pay/unifiedorder</a></td>
            <td><a asp-controller="WeChatPay" asp-action="AppPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>H5支付-统一下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=9_20&index=1" target="_blank">https://api.mch.weixin.qq.com/pay/unifiedorder</a></td>
            <td><a asp-controller="WeChatPay" asp-action="H5Pay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <td>小程序支付-统一下单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=9_1" target="_blank">https://api.mch.weixin.qq.com/pay/unifiedorder</a></td>
            <td><a asp-controller="WeChatPay" asp-action="LiteAppPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">7</th>
            <td>查询订单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_2" target="_blank">https://api.mch.weixin.qq.com/pay/orderquery</a></td>
            <td><a asp-controller="WeChatPay" asp-action="OrderQuery">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">8</th>
            <td>撤销订单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_11&index=3" target="_blank">https://api.mch.weixin.qq.com/secapi/pay/reverse</a></td>
            <td><a asp-controller="WeChatPay" asp-action="Reverse">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">9</th>
            <td>关闭订单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=9_3" target="_blank">https://api.mch.weixin.qq.com/pay/closeorder</a></td>
            <td><a asp-controller="WeChatPay" asp-action="CloseOrder">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">10</th>
            <td>申请退款</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_4" target="_blank">https://api.mch.weixin.qq.com/secapi/pay/refund</a></td>
            <td><a asp-controller="WeChatPay" asp-action="Refund">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">11</th>
            <td>查询退款</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_5" target="_blank">https://api.mch.weixin.qq.com/pay/refundquery</a></td>
            <td><a asp-controller="WeChatPay" asp-action="RefundQuery">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">12</th>
            <td>下载对账单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_6" target="_blank">https://api.mch.weixin.qq.com/pay/downloadbill</a></td>
            <td><a asp-controller="WeChatPay" asp-action="DownloadBill">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">13</th>
            <td>下载资金账单</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_18&index=7" target="_blank">https://api.mch.weixin.qq.com/pay/downloadfundflow</a></td>
            <td><a asp-controller="WeChatPay" asp-action="DownloadFundFlow">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">14</th>
            <td>企业付款到零钱</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2" target="_blank">https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers</a></td>
            <td><a asp-controller="WeChatPay" asp-action="Transfers">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">15</th>
            <td>查询企业付款零钱</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3" target="_blank">https://api.mch.weixin.qq.com/mmpaymkttransfers/gettransferinfo</a></td>
            <td><a asp-controller="WeChatPay" asp-action="GetTransferInfo">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">16</th>
            <td>企业付款到银行卡</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=24_2" target="_blank">https://api.mch.weixin.qq.com/mmpaysptrans/pay_bank</a></td>
            <td><a asp-controller="WeChatPay" asp-action="PayBank">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">17</th>
            <td>查询企业付款银行卡</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=24_3" target="_blank">https://api.mch.weixin.qq.com/mmpaysptrans/query_bank</a></td>
            <td><a asp-controller="WeChatPay" asp-action="QueryBank">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">18</th>
            <td>获取RSA加密公钥</td>
            <td><a href="https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=24_7&index=4" target="_blank">https://fraud.mch.weixin.qq.com/risk/getpublickey</a></td>
            <td><a asp-controller="WeChatPay" asp-action="GetPublicKey">立即测试</a></td>
        </tr>
    </tbody>
</table>

payment-dev/samples/WebApplicationSample/Views/WeChatPay/LiteAppPay.cshtml
@model WeChatPayLiteAppPayViewModel
@{
    ViewData["Title"] = "小程序支付-统一下单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPay" asp-action="LiteAppPay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="Body"></label>
                <input type="text" class="form-control" asp-for="Body" value="微信小程序支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="TotalFee"></label>
                <input type="text" class="form-control" asp-for="TotalFee" value="1" />
            </div>
            <div class="form-group">
                <label asp-for="SpBillCreateIp"></label>
                <input type="text" class="form-control" asp-for="SpBillCreateIp" value="127.0.0.1" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/wechatpay/unifiedorder" />
            </div>
            <div class="form-group">
                <label asp-for="TradeType"></label>
                <input type="text" class="form-control" asp-for="TradeType" value="JSAPI" />
            </div>
            <div class="form-group">
                <label asp-for="OpenId"></label>
                <input type="text" class="form-control" asp-for="OpenId" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
            <div class="form-group">
                <label>Parameter:</label>
                <textarea class="form-control" rows="3">@ViewData["parameter"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

payment-dev/samples/WebApplicationSample/Views/WeChatPay/OrderQuery.cshtml
@model WeChatPayOrderQueryViewModel
@{
    ViewData["Title"] = "查询订单";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPay" asp-action="OrderQuery">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TransactionId"></label>
                <input type="text" class="form-control" asp-for="TransactionId" />
            </div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

payment-dev/samples/WebApplicationSample/Views/WeChatPay/PayBank.cshtml
@model WeChatPayPayBankViewModel
@{
    ViewData["Title"] = "企业付款到银行卡";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="WeChatPay" asp-action="PayBank">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PartnerTradeNo"></label>
                <input type="text" class="form-control" asp-for="PartnerTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="EncBankNo"></label>
                <input type="text" class="form-control" asp-for="EncBankNo" />
            </div>
            <div class="form-group">
                <label asp-for="EncTrueName"></label>
                <input type="text" class="form-control" asp-for="EncTrueName" />
            </div>
            <div class="form-group">
                <label asp-for="BankCode"></label>
                <input type="text" class="form-control" asp-for="BankCode" />
            </div>
            <div class="form-group">
                <label asp-for="Amount"></label>
                <input type="text" class="form-control" asp-for="Amount" value="100" />
            </div>
            <div class="form-group">
                <label asp-for="Desc"></label>
                <input type="text" class="form-control" asp-for="Desc" value="企业付款到银行卡付款说明" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}